version: '2.0'

services:
  app:
    image: nlnetlabs/internetnl
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    dns: 127.0.0.1
    depends_on:
      - redis
      - rabbitmq
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=internetnl
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=internetnl_db1
