version: '2.0'

services:
  app:
    image: nlnetlabs/internetnl
    build:
      context: ..
      dockerfile: docker/Dockerfile
    dns: 127.0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - rabbitmq
      - postgres

  redis:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:alpine

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=internetnl
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=internetnl_db1
